package(default_visibility = ["//visibility:public"])

java_binary(
  name = "findepsilon",
  srcs = glob(["*.java"]),
  main_class = "com.games.findepsilon.Main",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/tictactoe:tictactoe",
  ],
)