package(default_visibility = ["//visibility:public"])

java_library(
  name = "chungtoi",
  srcs = glob(["*.java"]),
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/general:general",
    "//third_party:guava",
  ],
)
