package(default_visibility = ["//visibility:public"])

java_test(
  name = "montecarlo_episode_states",
  size = "small",
  srcs = ["MonteCarloAgentEpisodeStatesTest.java"],
  test_class = "com.games.agents.MonteCarloAgentEpisodeStatesTest",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/tictactoe:tictactoe",
    "//third_party:junit4",
    "//third_party:mockito",
  ]
)

java_test(
  name = "montecarlo_overall_returns",
  size = "small",
  srcs = ["MonteCarloAgentOverallReturnsTest.java"],
  test_class = "com.games.agents.MonteCarloAgentOverallReturnsTest",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/tictactoe:tictactoe",
    "//third_party:junit4",
    "//third_party:mockito",
  ]
)
