package(default_visibility = ["//visibility:public"])

java_test(
  name = "monte_carlo_get_best_action",
  size = "small",
  srcs = ["MonteCarloAgentGetBestActionTest.java"],
  test_class = "com.games.agents.MonteCarloAgentGetBestActionTest",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/tictactoe:tictactoe",
    "//third_party:junit4",
  ]
)

java_test(
  name = "monte_carlo_compute_cdf",
  size = "small",
  srcs = ["MonteCarloAgentComputeCDFTest.java"],
  test_class = "com.games.agents.MonteCarloAgentComputeCDFTest",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/tictactoe:tictactoe",
    "//third_party:junit4",
  ]
)

java_test(
  name = "monte_carlo_episode_states",
  size = "small",
  srcs = ["MonteCarloAgentEpisodeStatesTest.java"],
  test_class = "com.games.agents.MonteCarloAgentEpisodeStatesTest",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/tictactoe:tictactoe",
    "//third_party:junit4",
  ]
)

java_test(
  name = "monte_carlo_policy_evaluation",
  size = "small",
  srcs = ["MonteCarloAgentPolicyEvaluationTest.java"],
  test_class = "com.games.agents.MonteCarloAgentPolicyEvaluationTest",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/general:general",
    "//third_party:junit4",
    "//third_party:mockito",
  ]
)

java_test(
  name = "monte_carlo_state_action_counts",
  size = "small",
  srcs = ["MonteCarloAgentStateActionCountsTest.java"],
  test_class = "com.games.agents.MonteCarloAgentStateActionCountsTest",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/tictactoe:tictactoe",
    "//third_party:junit4",
  ]
)

java_test(
  name = "monte_carlo_update_policy",
  size = "small",
  srcs = ["MonteCarloAgentUpdatePolicyTest.java"],
  test_class = "com.games.agents.MonteCarloAgentUpdatePolicyTest",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/tictactoe:tictactoe",
    "//third_party:junit4",
    "//third_party:mockito",
  ]
)
