package(default_visibility = ["//visibility:public"])

java_test(
  name = "montecarlo",
  size = "small",
  srcs = ["MonteCarloAgentTest.java"],
  test_class = "com.games.agents.MonteCarloAgentTest",
  deps = [
    "//src/main/java/com/games/agents:agents",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/tictactoe:tictactoe",
    "//third_party:junit4",
    "//third_party:mockito",
  ]
)
