package(default_visibility = ["//visibility:public"])

java_test(
  name = "move_action",
  size = "small",
  srcs = ["ChungToiMoveActionTest.java"],
  test_class = "com.games.chungtoi.ChungToiMoveActionTest",
  deps = [
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//third_party:junit4",
  ]
)

java_test(
  name = "pass_action",
  size = "small",
  srcs = ["ChungToiPassActionTest.java"],
  test_class = "com.games.chungtoi.ChungToiPassActionTest",
  deps = [
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//third_party:junit4",
  ]
)

java_test(
  name = "put_action",
  size = "small",
  srcs = ["ChungToiPutActionTest.java"],
  test_class = "com.games.chungtoi.ChungToiPutActionTest",
  deps = [
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//third_party:junit4",
  ]
)

java_test(
  name = "token",
  size = "small",
  srcs = ["ChungToiTokenTest.java"],
  test_class = "com.games.chungtoi.ChungToiTokenTest",
  deps = [
    "//src/main/java/com/games/general:general",
    "//src/main/java/com/games/chungtoi:chungtoi",
    "//third_party:junit4",
  ]
)
